### ISSUE TITLE
Event Registration Record Role and Functions

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#10]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/object-field-resources/summit-event-reg-obj/

Review initial documentation: https://github.com/SFDO-Community/Summit-Events-App/wiki/3-%E2%80%93-View-and-Edit-Event-Registration

Intent: 
* Capture and articulate the role of the Event Registration record.
* Where can you see the records in Salesforce and what do the related lists mean on the parent and grandparent records?
* Capture reasons why you'd edit/update the event registration record (Check-in, process updates, etc.)

**Comment by rdblake21** [comment]
Closing this as it's articulated more in the other features and documentation.
