### ISSUE TITLE
Contributing to Summit Events  - review and transition to Pages site

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#14]
Move and review information here: https://github.com/SFDO-Community/Summit-Events-App/wiki/Contributing-to-Summit-Events

**Comment by dwhitig** [comment]
@rdblake21 I copied the existing text here but you may want to review and edit if needed:  https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/project-info/Contributing-to-Summit-Events.md

**Comment by rdblake21** [comment]
All transitioned to the new site as well as made some notes and link updates in the existing Wiki for redirects.
https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/project-info/Contributing-to-Summit-Events/
