### ISSUE TITLE
Document Additional Questions Feature

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#16]
Document the additional questions feature.  This is the 5 additional questions that can be used to ask questions of the registrants.  If more are needed, that will be covered under the Advanced Feature - Custom Questions.

Healey Sutton worked on May 2022 sprint
https://github.com/helix1027

Google doc: https://docs.google.com/document/d/1goNk46SFWc9RlM4px1WmUQCWybleZpTVmQFkvwKiIp8/edit?usp=sharing

**Comment by rdblake21** [comment]
@dwhitig is this one complete?

https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/additional-reg-questions/

**Comment by dwhitig** [comment]
@rdblake21 part of it is complete.  The additional reg questions themselves are documented but the Add’l Configuration & Options part is missing and still needs to be done.  
Healey Sutton had worked on it a bit and Matt Walters was guiding her but I think it needs to be reviewed then added as a mark down file.  Google doc: https://docs.google.com/document/d/1goNk46SFWc9RlM4px1WmUQCWybleZpTVmQFkvwKiIp8/edit?usp=sharing

**Comment by dwhitig** [comment]
Closing this as the additional standard questions documentation is complete.  Need another issue created for Add’l Configuration & Options documentation
