### ISSUE TITLE
Advanced Features header intro/insight

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#29]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/advanced-features/
Review: N/A
Intent:
* Setup what the person is seeing and the goals of the section.

**Comment by FrancisTR** [comment]
It seems that there is already text in the header intro/insight labeled "Here are some really cool features you can use in SEA." by @dwhitig I believe. Not sure if we needed more context, but will review the Advanced Feature section for further knowledge. Do let me know if anything!
