### ISSUE TITLE
Object Field Resources intro/insights

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#30]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/object-field-resources/
Review: N/A
Intent:
* Setup what the person is seeing and the goals of the section.
* Add context to the images and explain what they are seeing
* Subpages also need worked on

**Comment by FrancisTR** [comment]
@dwhitig @rdblake21 Is this already completed? It seems there are two images based on the link Ryan provided.

**Comment by rdblake21** [comment]
Closing this ticket as many of hte other features and documentation is solving for this
