### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#39]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/create-event-email/email-templates/
Review/Reference: https://help.salesforce.com/s/articleView?id=sf.admin_emailtemplates.htm&type=5
Intent: 
* Walk through the current process of creating the letter head and email template via the classic process.
* This may be a reference to the standard Salesforce functionality

Note: This is also serving as a placeholder for the future email functionality that'll leverage Lightning Email Templates

**Comment by ryannajackson** [comment]
We have agreed to remove this subpage and will update the current documentation with imagery and clarity.

**Comment by ryannajackson** [comment]
I updated the Create Event Email page with some clarifying edits, including some images. Can someone please remove the Email Template subpage? Thanks!

**Comment by FrancisTR** [comment]
> I updated the Create Event Email page with some clarifying edits, including some images. Can someone please remove the Email Template subpage? Thanks!

@ryannajackson. Removed the Subpage "Email Template". Will be deployed in the next Pull Request soon.

**Comment by dwhitig** [comment]
@rdblake21 Does this need review or can I can I close it?

**Comment by dwhitig** [comment]
@FrancisTR @ryannajackson can this be marked as completed or does it need further work/review?

**Comment by FrancisTR** [comment]
@dwhitig I talked to @ryannajackson about this issue a while back. It is done!

**Comment by dwhitig** [comment]
Excellent!
