### ISSUE TITLE
Event Hosts

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#40]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/Creating-an-event-host/
Review: This was already copied from the Wiki
Intent:
* Take the context of what exists and start to articulate the value, reason and intention of Events hosts
* How do you create Hosts and connect to Contacts
* Examples of when one would utilize Event hosts

Note: There is some functionality that this may need some love and overall needs some analysis for future intent.

**Comment by dwhitig** [comment]
Marking this as completed as I believe that it was reviewed by Ryan after I created.  Can reopen if needed.
