### ISSUE TITLE
Private Events

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#41]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/private-events/
Review: No Previous Documentation
Intent:
* What does having a Private Event means?
* Where does it not display, how would you market and what are some examples of having private event?
* How do you create a Private event and validate it isn't publicly visible.

**Comment by dwhitig** [comment]
Thank you Stefania!  Looks great - closing issue
