### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/summit-events-app-documentation#43]
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/advanced-features/capturing-payments/donations/
Review: No previous documentation
Intent:
* Articulate the need and desire to capture donations during the registration process
* Walk through how to create the right things in Salesforce to capture donations
* Walk through the registrant experience, less actually making the payment.
* Talk about different use cases and examples related to Donations only.

**Comment by koll2427** [comment]
I can try this one.

**Comment by koll2427** [comment]
I completed initial Donation Summary page and am willing to add more once the Donation allocation piece is fully functional.

**Comment by dwhitig** [comment]
This is great, thank you!  Let me know if you would like to work on another area outside of the sprint.
