### ISSUE TITLE
Add’l Configuration & Options

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#50]
Document the fields/features of the Add’l Configuration & Options tab on the Summit Events Page.
Give use cases where possible about how field settings might be used.

https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/standard-features/Event-Addl-Config-And-Options.md

**Comment by dwhitig** [comment]
@rdblake21 Page has been drafted.  Please review to see if format okay.  Also needs to have the Close Event Days Before and  Keep Registration Open During Event sections updated once the behavior is nailed down.

**Comment by rdblake21** [comment]
Review and updated @dwhitig
