### ISSUE TITLE
Guest Registrations

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#51]
Intent:
Document the guest registration process:
Set up to handle guest registration
Registration page behavior
Impact to registration records
Etc.

Update: https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/advanced-features/Guest-Registrations.md

Video of feature: https://cloud4good.zoom.us/rec/share/t1UzfcsmSCJZ4fnxINBmQ0rV3lvVVjrXbgKKDTqZ-uENNnESz_L2jB05PIlaUqWa.ORUBFEAODS0acp7O
Passcode: RE2THnE!

**Comment by rdblake21** [comment]
@dwhitig I'm going to close this issue as there are instructions up and posted.  Always happy to have some additional eyes, but I think we're in a good place!
