### ISSUE TITLE
Document BCC feature

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#57]
Document the BCC feature: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/create-event-email/bcc-registration-email/

**Comment by walt0019** [comment]
On the registration record, an Event Manager can manually add a(n) email(s) to the BCC Transactional Emails field on the Summit Events Registration record while selecting a corresponding status on the BCC Transactional Email Status field to allow for unique individuals to be added on triggered email communications to that specific registrant. A higher education use case may involve adding a coach or faculty member on a confirmation email that has the registrant’s itinerary on it as a reminder/notification.

Please note that if the Summit Events Email record includes an Action Sub status the Email will not send.  This functionality is limited to Summit Event Registration field Status and Summit Events Email field Action Status matching.  An enhancement request has been entered for the functionality to send regardless of Summit Events Email field Action Sub status.

**Comment by walt0019** [comment]
![Image](https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/assets/57462572/bc93ea7e-2068-416c-b04a-82913e958a74)

**Comment by dwhitig** [comment]
Marking this as complete as it looks like this was finished see:  https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/create-event-email/bcc-registration-email/
Thank you @walt0019 !
