### ISSUE TITLE
Document how to use the utm Tracking Codes

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#59]
How to use the utm Tracking Codes and where they populate
Release notes:  https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/release-notes/0-29-0-2/#analytics
No existing documentation

**Comment by rdblake21** [comment]
https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/advanced-features/utm-analytics/
